% ========================================================================
% COMPUTE_PAPER_METRICS: Calculate comprehensive DOA accuracy metrics
% ========================================================================
% This script processes MAT files containing DOA estimation results and
% computes detailed performance metrics including:
% - Per-angle RMSE and Soft-Accuracy (S-ACC)
% - End-fire region performance
% - Degradation span (angles with poor performance)
% ========================================================================

clear; clc; close all;

%% ===================== Config =====================
% Input MAT files generated by csv2mat.m
matFiles = {
    'C:\Users\25401\Desktop\End-Fire\result\DOA_results_1m.mat'
    'C:\Users\25401\Desktop\End-Fire\result\DOA_results_2m.mat'
};

outDir = 'C:\Users\25401\Desktop\End-Fire\result';
if ~exist(outDir, 'dir'), mkdir(outDir); end

% End-fire region: [20,40] U [140,160]
efRanges = [20 40; 140 160];

% Soft-accuracy scale and degraded threshold (aligned with draw.m)
softScaleDeg = 6;
degradedThr = 0.50;

% E_all / E_EF use "mean of per-angle RMSE".

%% ===================== Main =====================
summaryAll = table();
perAngleAll = table();

for f = 1:numel(matFiles)
    matPath = matFiles{f};
    if ~isfile(matPath)
        warning('Skip missing MAT file: %s', matPath);
        continue;
    end

    S = load(matPath);
    T = pick_table_from_struct(S);

    if ~ismember('TrueAngle', T.Properties.VariableNames)
        error('Missing TrueAngle in %s', matPath);
    end

    estCols = T.Properties.VariableNames(startsWith(T.Properties.VariableNames, 'Est_'));
    if isempty(estCols)
        error('No estimate columns (Est_*) found in %s', matPath);
    end

    [~, baseName, ~] = fileparts(matPath);
    conditionName = erase(baseName, 'DOA_results_');

    angles = unique(T.TrueAngle(~isnan(T.TrueAngle)));
    angles = sort(angles(:));

    if isempty(angles)
        warning('No valid angles in: %s', matPath);
        continue;
    end

    angleWidths = compute_angle_widths(angles);
    isEndFireAng = in_ranges(angles, efRanges);

    for m = 1:numel(estCols)
        methodCol = estCols{m};
        methodName = erase(methodCol, 'Est_');

        est = T.(methodCol);
        tru = T.TrueAngle;

        rmsePerAngle = nan(numel(angles),1);
        saccPerAngle = nan(numel(angles),1);
        nPerAngle = zeros(numel(angles),1);

        for a = 1:numel(angles)
            idx = (tru == angles(a));
            e = est(idx) - tru(idx);
            e = e(~isnan(e));

            nPerAngle(a) = numel(e);
            if isempty(e)
                continue;
            end

            rmsePerAngle(a) = sqrt(mean(e.^2));
            soft_score = 1 ./ (1 + (e/softScaleDeg).^2);
            saccPerAngle(a) = mean(soft_score, 'omitnan');
        end

        E_all = mean(rmsePerAngle, 'omitnan');
        E_EF = mean(rmsePerAngle(isEndFireAng), 'omitnan');

        S_ACC_EF = mean(saccPerAngle(isEndFireAng), 'omitnan');

        degradedMask = saccPerAngle < degradedThr;
        Deg_Span = sum(angleWidths(degradedMask), 'omitnan');

        oneRow = table( ...
            string(conditionName), string(methodName), E_all, E_EF, S_ACC_EF, Deg_Span, ...
            'VariableNames', {'Condition','Method','E_all','E_EF','S_ACC_EF','Deg_Span'});
        summaryAll = [summaryAll; oneRow]; %#ok<AGROW>

        tmpAngle = table( ...
            repmat(string(conditionName), numel(angles), 1), ...
            repmat(string(methodName), numel(angles), 1), ...
            angles, rmsePerAngle, saccPerAngle, nPerAngle, ...
            in_ranges(angles, efRanges), angleWidths, ...
            'VariableNames', {'Condition','Method','AngleDeg','RMSE','S_ACC','N','IsEndFire','AngleWidthDeg'});
        perAngleAll = [perAngleAll; tmpAngle]; %#ok<AGROW>
    end
end

%% ===================== Save =====================
outSummary = fullfile(outDir, 'paper_metrics_summary.csv');
outPerAngle = fullfile(outDir, 'paper_metrics_by_angle.csv');

if ~isempty(summaryAll)
    writetable(summaryAll, outSummary);
    fprintf('Saved summary metrics: %s\n', outSummary);
else
    warning('No summary rows to save.');
end

if ~isempty(perAngleAll)
    writetable(perAngleAll, outPerAngle);
    fprintf('Saved per-angle metrics: %s\n', outPerAngle);
end

%% ===================== Local Functions =====================
function T = pick_table_from_struct(S)
    fn = fieldnames(S);
    for i = 1:numel(fn)
        if istable(S.(fn{i}))
            T = S.(fn{i});
            return;
        end
    end
    error('No table variable found in MAT file.');
end

function tf = in_ranges(x, ranges)
    tf = false(size(x));
    for i = 1:size(ranges,1)
        tf = tf | (x >= ranges(i,1) & x <= ranges(i,2));
    end
end

function w = compute_angle_widths(angles)
% Compute per-angle represented angular width (deg) for non-uniform angle grids.
% For uniform 10-degree grids, each width will be ~10.
    a = sort(angles(:));
    n = numel(a);
    w = nan(n,1);

    if n == 1
        w(1) = 0;
        return;
    end

    mid = (a(1:end-1) + a(2:end)) / 2;
    leftEdge = a(1) - (mid(1) - a(1));
    rightEdge = a(end) + (a(end) - mid(end));
    edges = [leftEdge; mid; rightEdge];

    w = diff(edges);
end
